version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data